#임시 DB 도커 컴포즈
services:
  postgres:
    container_name: closet-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres-data: