services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433



volumes:
  postgres-data: