version: '3.8'

services:
  app:
    image: closet:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: closet
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - closet-network

  db:
    container_name: closet-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: closet
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - closet-network

#
#  cache-server:
#    container_name: closet-cache-server
#    image: redis:latest
#    ports:
#      - 6379:6379
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 30s

volumes:
  postgres-data:

networks:
  closet-network:
    driver: bridge
