server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/closet
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
