spring:
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APP_NAME:closet}
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.hibernate.jdbc.batch_size: 100

  batch:
    jdbc:
      initialize-schema: never

  # 임시 비밀번호 메일 전송
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:carer3759@gmail.com} # 임시 이메일
    password: ${MAIL_PASSWORD} # gamil 비번 아니 아니라 '앱 비밀번호' 발급 받고 ㄱ
    properties:
      mail:
        debug: true # dev
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000  # 나중에 recilence 도입하면 그거보다는 길게
        location: ${MAIL_LOCATION:localhost}
        from: ${MAIL_FROM:carer3759@gmail.com}  # 헤더에 한글 들어가는 것 때문

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

closet:
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  kakao:
    api:
      key: ${KAKAO_API_KEY}
  weather:
    api:
      key: ${WEATHER_API_KEY}
  storage:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET_NAME}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

jwt:
  secret: ${JWT_SECRET:44a81d8d4c44e07f56c9019fabb29194bd524d3018f79562d625749f7c709b5f} # 나중에 바꾸기
  header: ${JWT_HEADER:Authorization}
  expiration: ${JWT_EXPIRATION:3600}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:259200} # 3일
  refresh-header: ${JWT_REFRESH_HEADER:refresh_token}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    access-token-validity-seconds: ${SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS}

# Logging
logging:
  level:
    project.closet: debug
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace
