spring:
  profiles:
    active:
      - dev
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APP_NAME:closet}
    time-zone: "Asia/Seoul"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.hibernate.jdbc.batch_size: 100
    open-in-view: false

  batch:
    jdbc:
      initialize-schema: never

  # 임시 비밀번호 메일 전송
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
        from: ${MAIL_FROM:noreply@closet.com}
    default-encoding: UTF-8

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: off

closet:
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  kakao:
    api:
      key: ${KAKAO_API_KEY}
  weather:
    api:
      key: ${WEATHER_API_KEY}
  storage:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET_NAME}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    access-token-validity-seconds: ${SECURITY_JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${SECURITY_JWT_REFRESH_TOKEN_VALIDITY_SECONDS}

# Logging
logging:
  level:
    root: info

sse:
  timeout: 300_000 # 5분
